version: '3.9'

services:
  service:
    image: lichinin/simbirsoft_api
    hostname: 'service'
    container_name: 'service'
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy


  migrate:
    image: migrate/migrate
    volumes:
        - ./migrations:/migrations
    command: 
      - "-path=/migrations"
      - "-database=postgres://test:test@postgres:5432/test?sslmode=disable"
      - "up"
      - "3"    
    links: 
        - postgres
    depends_on:
      postgres:
        condition: service_healthy

