version: '3.9'

services:
  service:
    image: lichinin/simbirsoft_api
    hostname: 'service'
    container_name: 'service'
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy


  postgres: 
    image: postgres:15.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
     - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "test", "-U", "test" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
        - ./migrations:/migrations
    command: 
      - "-path=/migrations"
      - "-database=postgres://test:test@postgres:5432/test?sslmode=disable"
      - "up"
      - "3"    
    links: 
        - postgres
    depends_on:
      postgres:
        condition: service_healthy

